# Generated by Django 2.2.4 on 2019-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Subject', models.CharField(blank=True, max_length=200, null=True)),
                ('Text', models.TextField()),
                ('RetweetCount', models.IntegerField(default=0)),
                ('FavoriteCount', models.IntegerField(default=0)),
                ('FollowersCount', models.IntegerField(default=0)),
                ('Date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
