# Generated by Django 2.2.4 on 2019-08-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_plot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
